[package]
name = "CEP-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
roaring = "0.10.1"
serde = "1.0.164"
serde_json = "1.0.99"
tokio = { version="1.28.2", features=["full"]}
